### ISSUE TITLE
Баги в верстке

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#15]
1) На лендинге надо поправить z-index для выпадающих элементов:
![Выделение_859](https://user-images.githubusercontent.com/40715953/97971295-65614a80-1df5-11eb-86ba-6232c6522dbd.png)

2) В дропдауне очень мало места для текста, из-за чего он отображается не полностью. Надо сделать так, чтобы между инпутом и кнопкой не было отступа. Еще надо бы уточнить правила плюрализации: 21 гость, 22 гостя и. т. д. С младенцами, кажется, такая же проблема.
![Выделение_860](https://user-images.githubusercontent.com/40715953/97971396-8629a000-1df5-11eb-8a4e-93d665dfafff.png)

3) Мне кажется, на широком экране не очень красиво смотрится, что фоновые картинки занимают не всю ширину:
![Выделение_862](https://user-images.githubusercontent.com/40715953/97972554-4499f480-1df7-11eb-9980-9dc7e3ac44d9.png)
Сможешь сделать так, чтобы баннер занимал 100% ширины экрана, а весь остальной контент не растягивался больше 
 чем на 1440px?

4) Текущая страница в навигации должна быть выделена жирным:
![Выделение_866](https://user-images.githubusercontent.com/40715953/97975600-f509f780-1dfb-11eb-8ade-2c8607c86386.png)

**Comment by kv-work** [comment]
по 4му пункту все таки есть некоторые сомнения. Лендинг все таки не похож на страницу "о нас". Судя по footer'у там должна быть информация "о сервисе", "команде" и тп. К тому же в макете этот пункт не выделен. Раньше в макете UI Kit header&footers был еще одни пункт "Home" в header'е. Предлагаю решения: 1) оставить как есть (то есть не выделять пункт "о нас"); 2) Добавить пункт в навигацию "На главную"; 3) Принимаем все таки, что это страница "О нас"

**Comment by imin314** [comment]
> по 4му пункту все таки есть некоторые сомнения. Лендинг все таки не похож на страницу "о нас". Судя по footer'у там должна быть информация "о сервисе", "команде" и тп. К тому же в макете этот пункт не выделен. Раньше в макете UI Kit header&footers был еще одни пункт "Home" в header'е. Предлагаю решения: 1) оставить как есть (то есть не выделять пункт "о нас"); 2) Добавить пункт в навигацию "На главную"; 3) Принимаем все таки, что это страница "О нас"

Лучше тогда оставить, как есть

**Comment by imin314** [comment]
1) В футере частично появилась двойная линия:
![Выделение_874](https://user-images.githubusercontent.com/40715953/98357401-ba040000-2057-11eb-80e4-b6cd6de29ea9.png)

2) В стандартах компании не рекомендуется делать многоуровневые выпадающие меню с помощью ховер эффекта:
![Peek 2020-11-06 17-47](https://user-images.githubusercontent.com/40715953/98357739-3ac2fc00-2058-11eb-93e9-05648065750e.gif)

**Comment by imin314** [comment]
Если выбрать 0 взрослых, 0 детей и 1 младенец, результат будет выглядеть так:
![Выделение_964](https://user-images.githubusercontent.com/40715953/100431593-f52fa700-30ca-11eb-9505-a79617de9cfb.png)

**Comment by imin314** [comment]
Фон на странице cards обрезается, когда появляется скроллбар:
![Выделение_982](https://user-images.githubusercontent.com/40715953/100599302-6c1aa900-3332-11eb-945b-25a70111f0d2.png)

**Comment by imin314** [comment]
Что-то все равно криво фон отображается. Надо сделать так, чтобы серый цвет фона был задан для body, а контейнер .cards был спозиционирован по центру (логотип при этом остается привязанным к левому верхнему углу страницы).
![Выделение_999(028)](https://user-images.githubusercontent.com/40715953/101325255-084a3000-389e-11eb-9fdf-216c586d4724.png)

Аналогично для страниц colors-n-type, form-elements: тут логотип вообще уехал.
![Выделение_999(027)](https://user-images.githubusercontent.com/40715953/101325259-097b5d00-389e-11eb-9546-40fd3030cea5.png)

**Comment by imin314** [comment]
Поправь еще, пожалуйста, верстку этого блока:
![Выделение_999(029)](https://user-images.githubusercontent.com/40715953/101326638-257ffe00-38a0-11eb-9da9-ae4a0f3a791a.png)

В макете так:
![Выделение_999(030)](https://user-images.githubusercontent.com/40715953/101326720-447e9000-38a0-11eb-91d4-dae324a2b132.png)

**Comment by imin314** [comment]
Карусель с изображениями работает только на первой карточке:
![Выделение_014](https://user-images.githubusercontent.com/40715953/108349820-07c30380-7216-11eb-9953-695a025dac07.png)

**Comment by kv-work** [comment]
Больше нет картинок для остальных карточек =(. Если бы были другие картинки для остальных карточек, то карусель бы работала
