### ISSUE TITLE
Отзывчивая верстка

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#16]
Дальше пойдут возможно субъективные правки из-за моих эстетических предпочтений, так что можно обсудить их если что:

1) На ширине 1158px форма выбора номера прилипает к левой границе:
![Выделение_864](https://user-images.githubusercontent.com/40715953/97974386-123dc680-1dfa-11eb-8516-3aeaa363e40d.png)

**Comment by kv-work** [comment]
Поправимо. Возможно с точки зрения эстетики не очень красиво смотрится. Тут соглашусь)
