### ISSUE TITLE
Импорт scss

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#18]
Чтобы не приходилось, в каждом блоке создавать js для импорта стилей, лучше добавить один общий файл с импортом scss или настроить автоматический импорт стилей через js. В первом случае можно в src добавить подпапку style и туда вдобавок сложить main.scss, settings.scss.
https://github.com/kv-work/TOXIN_page/blob/5b867ced630bb0e9744f6f160bd8ecd2074e970e/src/components/button/button.js#L1

**Comment by kv-work** [comment]
Тогда у нас потеряется автономность блоков. По БЭМ все файлы относящиеся к одному блоку должны быть в одной папке.

**Comment by imin314** [comment]
Файл button.scss должен лежать в папке с блоком. Просто импортить его нужно где-то в глобальном файле.
