### ISSUE TITLE
Мелкие правки scss

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#19]
Эти 4 строчки стилей можно заменить сокращенным свойством. line-height лучше устанавливать коэффициентом, см. [тут](https://learn.javascript.ru/font-size-line-height#mnozhitel-dlya-line-height) почему.
![Выделение_875](https://user-images.githubusercontent.com/40715953/98362899-9e512780-2060-11eb-8e84-3098077329be.png)

Не нужно переопределять нижний padding, если это для того, чтобы подогнать верстку под PixelPerfect.
https://github.com/kv-work/TOXIN_page/blob/5b867ced630bb0e9744f6f160bd8ecd2074e970e/src/components/button/button.scss#L11-L13

Если отменяешь outline для псевдокласса focus, то надо все равно добавить стили, чтобы интерфейсом можно было пользоваться с клавиатуры.
https://github.com/kv-work/TOXIN_page/blob/5b867ced630bb0e9744f6f160bd8ecd2074e970e/src/components/button/button.scss#L23-L25

**Comment by imin314** [comment]
В медиа-запросах лучше использовать пиксели, а не относительные величины:
https://github.com/kv-work/TOXIN_page/blob/1887b856253fa59736d72994071a61434f8a9a21/src/pages/cards/cards.scss#L10

**Comment by imin314** [comment]
По стандартам нельзя двигать элементы через position: relative.
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/pages/cards/cards.scss#L13-L20

Лэйаут этой страницы получился сложным для понимания. Для начала надо понять, какое поведение тебе нужно реализовать:
1) Если нужно, чтобы логотип всегда располагался относится левого угла окна браузера, то делай через position: absolute.
2) Если нужно, чтобы при достижении какой-то ширины экрана, логотип не двигался, то можно .cards задать max-width, а logo-wrapper cпозиционировать с помощью padding у cards.
![Выделение_983](https://user-images.githubusercontent.com/40715953/100596619-f6610e00-332e-11eb-9397-e31aa89a8f11.png)

**Comment by imin314** [comment]
Надо в целом поправить лэйаут на этой странице:
1) Верхний отступ задается padding на .cards, причем его можно не делать таким большим, чтобы не пришлось двигать логотип через position: relative. А нижний элементом в колонке. Лучше им также управлять в .cards.
2) Из-за того, что последняя колонка шире ее контента, выравнивание на странице сбивается.
![Выделение_984](https://user-images.githubusercontent.com/40715953/100598315-25787f00-3331-11eb-91bf-0f3165fcaded.png)
![Выделение_985](https://user-images.githubusercontent.com/40715953/100598322-28736f80-3331-11eb-9997-aee0371c13b9.png)

Этот селектор не соответствует стандартам:
![Выделение_986](https://user-images.githubusercontent.com/40715953/100599005-0d552f80-3332-11eb-9a22-91566cd972d0.png)
Вместо селекторов по-тегам используй элементы-обертки, а еще nth-child(n) выбирает все элементы, так что в нем нет смысла.

**Comment by imin314** [comment]
Надо глобально еще поправить стили таких элементов:
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/components/comment-block/comment-block.scss#L20-L23

**Comment by imin314** [comment]
Сейчас высота блока cards 100%, но т. к. у родителя (body) не задана высота, то % не работают. Нужно задать html высоту 100% (с корневым элементов высота в % работает), задать 100% у body и тогда под страницей не будет белой полосы.
![Выделение_999(075)](https://user-images.githubusercontent.com/40715953/102468349-faf22a00-4083-11eb-81ff-9b951da368c3.png)

**Comment by imin314** [comment]
В html надо указать дефолтные цвета фона и текста, размер и семейство шрифта. Смотри [стандарты](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.7).
https://github.com/kv-work/TOXIN_page/blob/19b746ee5ab5959d54c748db3ac5198a7c5a45c5/src/main.scss#L7-L12

Не используй глобальные стили по тегам ([пункт 4.4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.4)):
https://github.com/kv-work/TOXIN_page/blob/19b746ee5ab5959d54c748db3ac5198a7c5a45c5/src/main.scss#L14-L24

Не нужно прописывать лишние стили ([пункт 2.10](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.10)):
https://github.com/kv-work/TOXIN_page/blob/19b746ee5ab5959d54c748db3ac5198a7c5a45c5/src/main.scss#L34-L38
В данном случае margin и padding обнулять у body не нужно.

**Comment by imin314** [comment]
1) То, что ниже идут стили инпута и так ясно из названия селектора, комментарий можно удалить: 
https://github.com/kv-work/TOXIN_page/blob/485514e5bad4aee2fe99cc7e6be22c06772f100a/src/components/dropdown/dropdown.scss#L10-L12
2) Эти кнопки являются частью плагина ведь? Если да, то надо убрать код в `// editing plugin styles`. 
https://github.com/kv-work/TOXIN_page/blob/485514e5bad4aee2fe99cc7e6be22c06772f100a/src/components/dropdown/dropdown.scss#L29-L36

**Comment by imin314** [comment]
По стандартам мы не используем селекторы по тегам. Чтобы скрыть содержимое header__nav-bar, можно добавить обертку для navBar() и скрывать ее.
![Выделение_024](https://user-images.githubusercontent.com/40715953/105940031-f1011500-608c-11eb-879c-ebbd786efa02.png)

**Comment by kv-work** [comment]
Стили для фокуса заданы согласно макету:
```css
border-color: $dark-50
```

**Comment by imin314** [comment]
Для состояния фокуса нет стилей:
https://github.com/kv-work/TOXIN_page/blob/ac39c180b29fe0d02ab6a0d3c7d89bd99c042822/src/components/rate-button/rate-button.scss#L29-L31
