### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#21]
Каждый блок должен быть в отдельной папке:
https://github.com/kv-work/TOXIN_page/blob/eccf7173b7fdcf35fed03bc97943020974096c24/src/components/bullet-list/bullet-list.pug#L1-L10

**Comment by kv-work** [comment]
У нас bulletListItem существует только внутри bulletList) Есть ли смысл для него создавать отдельную папку?

**Comment by kv-work** [comment]
По сути это элемент, а не блок

**Comment by imin314** [comment]
Мне кажется, если это элемент, то лучше его не оформлять через миксин, чтобы его нельзя было использовать вне bulletList.

**Comment by kv-work** [comment]
Согласен, так и стоило поступить. Исправлю

**Comment by imin314** [comment]
https://github.com/kv-work/TOXIN_page/blob/eccf7173b7fdcf35fed03bc97943020974096c24/src/components/bullet-list/bullet-list.pug#L1-L15
Здесь есть еще несколько правок:
1) Класс должен соответствовать названию блока: .bullet-list
2) lh - это устаревший тег. Нашла его описание только в устаревшем черновике спецификации от 1995 г. И судя по нему, он должен быть первым потомком тега `<ul>`. Но в любом случае не нужно его использовать.
3) Сейчас блок bullet-list состоит только из элементов label, list, item. Может, сделать этот блок более универсальным, убрав название? Тогда миксин будет возвращать ul.bullet-list и его item'ы. Ну или добавить обертку .bullet-list. Все-таки блок - это сущность, он должен быть представлен конкретным тегом, как мне кажется.

**Comment by imin314** [comment]
> Мне кажется, если это элемент, то лучше его не оформлять через миксин, чтобы его нельзя было использовать вне bulletList.

Похожая проблема есть в блоке checkbox. В этой папке лежит два блока option и checkboxList. Option - это просто чекбокс, его можно спокойно выносить в самостоятельный блок, т. к. он может использоваться не только в списке, а и в отдельных формах. Дальше посмотрим на проблемы блока checkboxList:
1) Класс блока должен совпадать с названием блока:
https://github.com/kv-work/TOXIN_page/blob/eccf7173b7fdcf35fed03bc97943020974096c24/src/components/checkbox/checkbox.pug#L6
2) Почему используется switch вместо if? Может же быть раскрывающийся список с деталями для чекбоксов.
https://github.com/kv-work/TOXIN_page/blob/eccf7173b7fdcf35fed03bc97943020974096c24/src/components/checkbox/checkbox.pug#L7-L16
3) Не нужно добавлять второй модификатор для expandable_opened, лучше в scss добавить стиль для элемента с двумя классами expandable и opened.

**Comment by imin314** [comment]
Для этого класса нет стилей, его можно не добавлять?:
https://github.com/kv-work/TOXIN_page/blob/1887b856253fa59736d72994071a61434f8a9a21/src/components/checkbox-list/checkbox-list.pug#L20

**Comment by kv-work** [comment]
По-моему где то было, описано, что у каждого элемента должен быть класс, или я путаю) Ведь возможно в будущем мы захотим как то стилизовать этот элемент. На этот случай у нас уже стоит подходящий класс)

**Comment by imin314** [comment]
Здесь класс у блока уже есть: checkbox-list, а модификатор rich ему не нужен, т. к. эта опция передается checkbox-option.

**Comment by imin314** [comment]
Здесь элемент создан не по БЭМ, у него должен быть основной класс и класс модификатора:
![Выделение_020](https://user-images.githubusercontent.com/40715953/105938404-18a2ae00-608a-11eb-98cc-adee82103d86.png)

**Comment by imin314** [comment]
В БЭМ пробелы в названии элемента заменяются на дефисы:
![Выделение_087](https://user-images.githubusercontent.com/40715953/108019315-89673580-704c-11eb-892f-8040b6c47d85.png)
Но эти классы не используются в блоке, поэтому их можно удалить.

**Comment by imin314** [comment]
Здесь проблема в том, что если nested === true, то у компонента не будет класса блока (только класс с модификатором nested).
![Выделение_090](https://user-images.githubusercontent.com/40715953/108021181-98e87d80-7050-11eb-87d8-b430d9c5e1d6.png)

**Comment by imin314** [comment]
В булевых модификаторах пробел заменяется дефисом:
![Выделение_038](https://user-images.githubusercontent.com/40715953/109461992-7cf3cb80-7a95-11eb-8209-1a8dac22bb9a.png)

**Comment by imin314** [comment]
В disabled состоянии у блока нет основного класса:
![Выделение_042](https://user-images.githubusercontent.com/40715953/109463308-58005800-7a97-11eb-9a02-bb88ede33b81.png)

**Comment by imin314** [comment]
Здесь лучше использовать модификатор "ключ-значение":
![Выделение_043](https://user-images.githubusercontent.com/40715953/109464093-ad893480-7a98-11eb-90e6-a6e63dd87402.png)
