### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#22]
Блок довольно объемный, буду сюда добавлять ишьюзы по нему, но исправления нужно вносить глобально.

1) Сторонние библиотеки надо по возможности импортить из node_modules (air-datepicker вроде есть в npm):
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/components/datepicker-block/Datepicker.js#L1

2) Можно в js вместо hasClass('start-date') искать hasClass('js-datepicker_separated')? А зачем, кстати, добавлять data-separated?
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/components/datepicker-block/datepicker-block.pug#L4

3) js-классы не используются для стилизации:
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/components/datepicker-block/datepicker-block.scss#L11-L13

4) Для чего здесь `&attributes(attributes)`? Его лучше не использовать, потому что он позволяет элементу из стороннего блока добавить любые классы (=миксы).
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/components/datepicker-block/datepicker-block.pug#L14

5) Элементу .datepicker-block__input почему-то добавляются классы .js-datepicker. 
https://github.com/kv-work/TOXIN_page/blob/180aceb4d78c997f4fb098a492c7164daf20a4bd/src/components/datepicker-block/datepicker-block.pug#L4-L11
Ну и в целом тут можно как-то попроще написать. Например:
```
    let classList = 'datepicker-block js-datepicker-block'; // класс js-datepicker должен быть для любого варианта
    if (inline) {
      classList += 'js-datepicker-block__inline';
    } ....
```
Для input не вижу смысла дублировать те же классы с модификаторами, если можно в js искать '.js-datepicker-block__separated .js-datepicker-block__input', а в js-datepicker__masked, наверное, нет смысла, т. к. этот класс добавляется только для separated.

В плане именования, мне кажется, слово block избыточное. Просто datepicker уже отражает суть того, что это за компонент такой.

**Comment by kv-work** [comment]
2. В целом наверно и не нужна data-separated) Наверно в одной из реализаций использовал, или хотел использовать, а потом не подчистил)

**Comment by imin314** [comment]
Продолжение:)
1) Все описательные комментарии к методам надо удалить. Что делает метод должно быть понятно из его названия, тонкости реализации (например, что значения берутся из data-атрибудтов) комментировать не нужно, это должно быть понятно из тела метода:
https://github.com/kv-work/TOXIN_page/blob/3dd46d5908566bf41a338a3b4f56e0f24a157a9c/src/components/datepicker-block/Datepicker.js#L70
Такие описательные комментарии вообще допустимо добавлять, но в исключительных случаях. Например, когда в коде есть какая-то нелогичная часть, типа баг фикса.

**Comment by kv-work** [comment]
Класс .datepicker используется внутри самого плагина. К тому же у нас не только datepicker а блок, в котором используется datepicker. В блоке также присутствует заголовок (или заголовки в случае двух инпутов) блока, дополнительный инпут (в разделенном варианте). Поэтому название datepicker-block больше отражает суть компонента

**Comment by imin314** [comment]
> Класс .datepicker используется внутри самого плагина. К тому же у нас не только datepicker а блок, в котором используется datepicker. В блоке также присутствует заголовок (или заголовки в случае двух инпутов) блока, дополнительный инпут (в разделенном варианте). Поэтому название datepicker-block больше отражает суть компонента

Ясно, ну пускай тогда остается datepicker-block.

**Comment by imin314** [comment]
1) Немного странное условие, т. к. datepicker-block это класс по умолчанию, надо его добавить в `let classListBlock = 'js-datepicker-block';`
https://github.com/kv-work/TOXIN_page/blob/3eeb776457f5c046d84ca050e60571bcf25f818b/src/components/datepicker-block/datepicker-block.pug#L4-L11

**Comment by imin314** [comment]
https://github.com/kv-work/TOXIN_page/blob/9fcc4ef1cab701dabd9bd59eec9f23672abd8116/src/components/datepicker-block/datepicker-block.pug#L11
&attributes(attributes) лучше убрать глобально, иначе блоку можно добавлять другие классы (миксы). 
Такие параметры просто передавай через опции: https://github.com/kv-work/TOXIN_page/blob/9fcc4ef1cab701dabd9bd59eec9f23672abd8116/src/pages/cards/cards.pug#L31

**Comment by imin314** [comment]
1. Не поправлено
2. Надо глобально поправить
![Выделение_018](https://user-images.githubusercontent.com/40715953/105937970-33285780-6089-11eb-81fe-e8db7306d7f4.png)
3. Поправить глобально
![Выделение_019](https://user-images.githubusercontent.com/40715953/105938025-53f0ad00-6089-11eb-820d-6a4d022efd9d.png)
