### ISSUE TITLE
Импорт зависимостей

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#24]
Плагины нужно по возможности устанавливать в node_modules:
https://github.com/kv-work/TOXIN_page/blob/485514e5bad4aee2fe99cc7e6be22c06772f100a/src/components/dropdown/dropdown.js#L2

Этот вроде есть в npm: https://www.npmjs.com/package/item-quantity-dropdown

**Comment by kv-work** [comment]
Данный плагин установлен в node_modules. Однако если прописать просто 
`import 'item-quantity-dropdown'`
то функционал не будет работать, так как компилятор не может найти модуль. Поэтому приходится прописывать полный путь к скрипту модуля
