### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#26]
Может, дефолтный язык подгружать из общего файла с настройками? А то если не указать язык, то один блок будет на английском, другой - на русском.
![Выделение_023](https://user-images.githubusercontent.com/40715953/105939659-40931100-608c-11eb-9476-544cd9ed6be9.png)

![Выделение_022](https://user-images.githubusercontent.com/40715953/105939656-3f61e400-608c-11eb-821d-69c8d64caf25.png)

**Comment by imin314** [comment]
По стандартам airbnb нужно использовать явное преобразование к числам:
![Выделение_027](https://user-images.githubusercontent.com/40715953/105941269-a1701880-608f-11eb-9eec-a1b37c4e3f5d.png)

**Comment by imin314** [comment]
Зачем здесь id? Надо найти способ обойтись без него:
![Выделение_034](https://user-images.githubusercontent.com/40715953/105942283-7edeff00-6091-11eb-9cb0-4df3e8463a4c.png)

**Comment by imin314** [comment]
Нужно переписать циклы for на встроенные методы массивов ([см. стандарты](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.15)):
![image](https://user-images.githubusercontent.com/40715953/105942709-599ec080-6092-11eb-8ef7-9daae078a68d.png)

**Comment by imin314** [comment]
Опечатка: ![Выделение_038](https://user-images.githubusercontent.com/40715953/105943044-ffeac600-6092-11eb-91ba-cc92dd944986.png)

**Comment by kv-work** [comment]
[dataSource](https://pagination.js.org/docs/index.html) отвечает за источник данных. Вызов функции происходит внутри самого плагина. По всей видимости при использовании функции в качестве источника данных, необходимо обязательно внутри функции после формирования массива с данными `result` прописывать вызов `done(result) `, для рендеринга этого массива. Сам колбэк (done) по всей видимости передается внутри самого плагина.

**Comment by imin314** [comment]
Я не сразу обратила внимание, что в некоторых блоках настройка языка используется, чтобы добавить модификатор для позиционирования. Мне кажется, не стоит завязываться на локали, т. к. это неочевидная настройка. Нужно переименовать модификатор на подходящий.
![Выделение_085](https://user-images.githubusercontent.com/40715953/108018831-6425f780-704b-11eb-8bd1-52e632527f5a.png)

**Comment by imin314** [comment]
В такие случаях нужно использовать шаблонные строки вместо конкатенации строк: ![Выделение_012](https://user-images.githubusercontent.com/40715953/108348662-a64e6500-7214-11eb-99b7-5d4bb863b122.png)

**Comment by imin314** [comment]
Оператор инкремента не рекомендуется использовать по стандартам [airbnb](https://github.com/airbnb/javascript#variables--unary-increment-decrement):
![Выделение_018](https://user-images.githubusercontent.com/40715953/108352211-2080e880-7219-11eb-893f-c5f88fadf508.png)
