### ISSUE TITLE
Правки по js

### ISSUE THREAD

**Issue by imin314** [kv-work/TOXIN_page#27]
Нужно [кэшировать элементы](https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#7.1):
![Выделение_029](https://user-images.githubusercontent.com/40715953/105941426-ff046500-608f-11eb-83b4-8f575dfd472a.png)

**Comment by kv-work** [comment]
Добавил кеширование элементов при исправлении .js файлов по другим issues
